server:
  port: 9052

spring:
  application:
    name: webflux
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zglu

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/