server:
  port: 9001

spring:
  application:
    name: sys

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.16.50.220:3306/zglu_sys?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/